name: Upload to Tencent Cloud COS

# Required GitHub Secrets:
# - TENCENT_SECRET_ID: 腾讯云API密钥ID
# - TENCENT_SECRET_KEY: 腾讯云API密钥Key
# - TENCENT_COS_BUCKET: 腾讯云存储桶名称
# - TENCENT_COS_REGION: 腾讯云存储区域 (如: ap-beijing, ap-shanghai等)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to upload (e.g. v1.0.0)'
        required: true
        default: 'v0.0.1'

permissions:
  contents: read

jobs:
  upload-to-cos:
    runs-on: ubuntu-latest
    environment: default
    env:
      COS_DIRECTORY: "auto_updater"
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          # 安装 coscmd 用于文件操作
          pip install coscmd

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建下载目录
          mkdir -p downloads

          # 获取发布信息
          echo "正在获取发布信息: ${{ github.event.inputs.release_tag }}"
          RELEASE_INFO=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_tag }}")

          # 检查API响应是否成功
          if echo "$RELEASE_INFO" | jq -e '.message' > /dev/null 2>&1; then
            echo "错误：无法获取发布信息"
            echo "$RELEASE_INFO" | jq -r '.message'
            exit 1
          fi

          # 检查是否有资源文件
          ASSET_COUNT=$(echo "$RELEASE_INFO" | jq -r '.assets | length')
          echo "找到 $ASSET_COUNT 个资源文件"

          if [ "$ASSET_COUNT" -eq 0 ]; then
            echo "警告：该发布版本没有资源文件"
            exit 1
          fi

          # 解析并下载每个资源文件
          echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | test("\\.(exe|dmg|zip|yml|blockmap)$")) | .browser_download_url + " " + .name' > download_list.txt

          # 检查是否有匹配的文件
          if [ ! -s download_list.txt ]; then
            echo "错误：没有找到匹配的文件类型 (exe, dmg, zip, yml, blockmap)"
            echo "可用的资源文件："
            echo "$RELEASE_INFO" | jq -r '.assets[].name'
            exit 1
          fi

          # 下载文件
          while IFS=' ' read -r url filename; do
            echo "正在下载 $filename 从 $url"
            if curl -L -H "Authorization: token $GH_TOKEN" "$url" -o "downloads/$filename"; then
              echo "✓ 成功下载: $filename"
            else
              echo "✗ 下载失败: $filename"
              exit 1
            fi
          done < download_list.txt

          # 清理临时文件
          rm -f download_list.txt

          # 列出已下载的文件
          echo "已下载的文件:"
          ls -la downloads/

          # 验证下载目录不为空
          if [ ! "$(ls -A downloads/)" ]; then
            echo "错误：下载目录为空"
            exit 1
          fi
        
      
      - name: Upload to Tencent Cloud COS
        run: |
          # 配置 coscmd
          echo "正在配置 coscmd..."
          coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} -s ${{ secrets.TENCENT_SECRET_KEY }} -b ${{ secrets.TENCENT_COS_BUCKET }} -r ${{ secrets.TENCENT_COS_REGION }}

          # 验证配置
          echo "验证 COS 连接..."
          if ! coscmd info > /dev/null 2>&1; then
            echo "错误：无法连接到腾讯云 COS，请检查配置"
            exit 1
          fi

          # 检查下载目录
          echo "检查下载目录..."
          if [ ! -d "downloads" ]; then
            echo "错误：downloads 目录不存在"
            exit 1
          fi

          cd downloads
          if [ ! "$(ls -A .)" ]; then
            echo "错误：下载目录中没有找到文件！"
            exit 1
          fi

          echo "准备上传的文件："
          ls -la

          # 检查目标目录是否存在并删除其中的文件
          echo "检查目录 ${{ env.COS_DIRECTORY }} 是否存在..."
          if coscmd list ${{ env.COS_DIRECTORY }}/ > /dev/null 2>&1; then
            echo "目录 ${{ env.COS_DIRECTORY }} 存在，正在删除其中的文件..."

            # 获取 COS_DIRECTORY 中的文件和子目录列表
            coscmd list ${{ env.COS_DIRECTORY }}/ > ../file_list.txt 2>/dev/null || {
              echo "警告：无法列出目录中的文件"
            }

            # 删除 COS_DIRECTORY 中的每个文件和子目录
            while IFS= read -r line; do
              if [[ "$line" =~ ^[[:space:]]*[0-9]+ ]] || [[ "$line" =~ ^[[:space:]]*DIR ]]; then
                # 从行中提取文件/目录路径
                item_path=$(echo "$line" | awk '{print $NF}')
                if [[ "$item_path" == *"${{ env.COS_DIRECTORY }}/"* ]] && [[ "$item_path" != "${{ env.COS_DIRECTORY }}/" ]]; then
                  echo "正在删除: $item_path"
                  if [[ "$item_path" == *"/" ]]; then
                    # 这是一个目录
                    coscmd delete -r "$item_path" || echo "警告：删除 $item_path 失败"
                  else
                    # 这是一个文件
                    coscmd delete "$item_path" || echo "警告：删除 $item_path 失败"
                  fi
                fi
              fi
            done < ../file_list.txt

            rm -f ../file_list.txt
          else
            echo "目录 ${{ env.COS_DIRECTORY }} 不存在，将在上传时创建..."
          fi

          # 上传新文件到 COS_DIRECTORY 的子目录中
          echo "开始上传新文件..."

          # 创建子目录路径: COS_DIRECTORY/latest/
          UPLOAD_PATH="${{ env.COS_DIRECTORY }}/latest"
          UPLOAD_COUNT=0

          for file in *; do
            if [[ -f "$file" ]]; then
              echo "正在上传 $file 到 $UPLOAD_PATH/$file"
              if coscmd upload "$file" "$UPLOAD_PATH/$file"; then
                echo "✓ 成功上传: $file"
                ((UPLOAD_COUNT++))
              else
                echo "✗ 上传失败: $file"
                exit 1
              fi
            fi
          done

          if [ $UPLOAD_COUNT -eq 0 ]; then
            echo "错误：没有文件被上传"
            exit 1
          fi

          echo "上传完成！共上传 $UPLOAD_COUNT 个文件"
          echo "文件已上传到: $UPLOAD_PATH/"