name: Upload to Tencent Cloud COS

# Required GitHub Secrets:
# - TENCENT_SECRET_ID: 腾讯云API密钥ID
# - TENCENT_SECRET_KEY: 腾讯云API密钥Key
# - TENCENT_COS_BUCKET: 腾讯云存储桶名称
# - TENCENT_COS_REGION: 腾讯云存储区域 (如: ap-beijing, ap-shanghai等)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to upload (e.g. v1.0.0)'
        required: true
        default: 'v0.0.1'

permissions:
  contents: read

jobs:
  upload-to-cos:
    runs-on: ubuntu-latest
    environment: default
    env:
      COS_DIRECTORY: "auto_updater"
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          # Install coscmd for file operations
          pip install coscmd

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create downloads directory
          mkdir -p downloads
          
          # Get release info
          RELEASE_INFO=$(curl -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_tag }}")
          
          # Parse and download each asset
          echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | test("\\.(exe|dmg|zip|yml|blockmap)$")) | .browser_download_url + " " + .name' | while read url filename; do
            echo "Downloading $filename from $url"
            curl -L -H "Authorization: token $GH_TOKEN" "$url" -o "downloads/$filename"
          done
          
          # List downloaded files
          echo "Downloaded files:"
          ls -la downloads/
        
      
      - name: Upload to Tencent Cloud COS
        run: |
          # Configure coscmd
          coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} -s ${{ secrets.TENCENT_SECRET_KEY }} -b ${{ secrets.TENCENT_COS_BUCKET }} -r ${{ secrets.TENCENT_COS_REGION }}
          
          # Get current timestamp for backup
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          
          # Check if the target directory exists and backup it
          echo "Checking if directory ${{ env.COS_DIRECTORY }} exists..."
          if coscmd list ${{ env.COS_DIRECTORY }}/ > /dev/null 2>&1; then
            echo "Directory ${{ env.COS_DIRECTORY }} exists, creating backup..."
            
            # Create backup by downloading and re-uploading with new prefix
            echo "Creating backup: ${{ env.COS_DIRECTORY }}_backup_${TIMESTAMP}"
            
            # Download all files in the directory to local temp folder
            mkdir -p backup_temp
            coscmd download -r ${{ env.COS_DIRECTORY }}/ backup_temp/
            
            # Upload to backup location with correct path structure
            cd backup_temp
            coscmd upload -r ${{ env.COS_DIRECTORY }}/ ${{ env.COS_DIRECTORY }}_backup_${TIMESTAMP}/
            cd ..
            
            # Clean up temp directory
            rm -rf backup_temp
            
            # Delete original directory after backup
            echo "Deleting original directory ${{ env.COS_DIRECTORY }}..."
            coscmd delete -r ${{ env.COS_DIRECTORY }}/
          else
            echo "Directory ${{ env.COS_DIRECTORY }} does not exist, proceeding with upload..."
          fi
          
          # Upload new files to COS_DIRECTORY
          cd downloads
          for file in *; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to ${{ env.COS_DIRECTORY }}/${{ github.event.inputs.release_tag }}/$file"
              coscmd upload "$file" "${{ env.COS_DIRECTORY }}/${{ github.event.inputs.release_tag }}/$file"
            fi
          done
          
          echo "Upload completed successfully!"
          echo "Files uploaded to: ${{ env.COS_DIRECTORY }}/${{ github.event.inputs.release_tag }}/"
          echo "Backup directory (if created): ${{ env.COS_DIRECTORY }}_backup_${TIMESTAMP}"